apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "openstatus.configMapName" . }}
  labels:
    {{- include "openstatus.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.config.DATABASE_URL | default (printf "http://%s:%s" (include "openstatus.libsqlHost" .) (toString .Values.libsql.service.httpPort)) | quote }}
  DATABASE_AUTH_TOKEN: {{ .Values.config.DATABASE_AUTH_TOKEN | quote }}
  NODE_ENV: {{ .Values.config.NODE_ENV | quote }}
  FLY_REGION: {{ .Values.config.FLY_REGION | quote }}
  SELF_HOST: {{ .Values.config.SELF_HOST | quote }}
  NEXT_PUBLIC_URL: {{ .Values.config.NEXT_PUBLIC_URL | quote }}
  TURBO_ENV_MODE: {{ .Values.config.TURBO_ENV_MODE | quote }}
  {{- if .Values.tinybird.enabled }}
  TINYBIRD_URL: "http://{{ include "openstatus.tinybirdHost" . }}:{{ .Values.tinybird.service.port }}"
  {{- end }}
  {{- if and .Values.redis.enabled .Values.serverlessRedisHttp.enabled }}
  UPSTASH_REDIS_REST_URL: "http://{{ include "openstatus.srhHost" . }}:{{ .Values.serverlessRedisHttp.service.port }}"
  UPSTASH_REDIS_REST_TOKEN: {{ .Values.serverlessRedisHttp.token | quote }}
  {{- end }}
