{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstatus.fullname" . }}-redis
  labels:
    {{- include "openstatus.componentLabels" (dict "context" . "component" "redis") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "openstatus.selectorLabels" (dict "context" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "openstatus.componentLabels" (dict "context" . "component" "redis") | nindent 8 }}
    spec:
      {{- include "openstatus.imagePullSecrets" . | nindent 6 }}
      containers:
        - name: redis
          image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          resources:
            {{- toYaml .Values.redis.resources | nindent 12 }}
{{- end }}
