{{- if not .Values.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openstatus.secretName" . }}
  labels:
    {{- include "openstatus.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- $skipKeys := dict }}
  {{- if and $.Values.redis.enabled $.Values.serverlessRedisHttp.enabled }}
  {{- $_ := set $skipKeys "UPSTASH_REDIS_REST_URL" true }}
  {{- $_ := set $skipKeys "UPSTASH_REDIS_REST_TOKEN" true }}
  {{- end }}
  {{- range $key, $value := .Values.secrets }}
  {{- if not (hasKey $skipKeys $key) }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
